name: labeler

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: labeler action
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"
